spring:
  application:
    name: service-under-test
  cloud:
    stream:
      bindings:
        sample-input:
          destination: sample-topic
          group: ${spring.application.name}
    gcp:
      pubsub:
        emulator-host: pubsub-emulator:8085
        project-id: fake
  data:
    mongodb:
      uri: mongodb://user:pass@mongodb:27017/resilience-workshop?retryWrites=true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  health:
    binders:
      enabled: false
    mongo:
      enabled: false
faulty-service:
  url: http://faulty-service
