image:
  tag: 3.6
auth:
  enabled: true
  username: user
  password: pass
  database: resilience-workshop
resources:
  limits:
     cpu: 50m
     memory: 200Mi
  requests:
     cpu: 50m
     memory: 200Mi
persistence:
  enabled: false
nodeSelector:
  node_pool: preemptible
tolerations:
  - key: preemptible
    operator: Equal
    value: "true"
    effect: NoSchedule
