{
 "title": "resilience-workshop",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{namespace=\"resilience-workshop\"}) by (pod)",
     "legendFormat": "live {{pod}}"
    },
    {
     "expr": "sum(jvm_threads_daemon_threads{namespace=\"resilience-workshop\"}) by (pod)",
     "legendFormat": "daemon {{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"resilience-workshop\",pod=~\"service-under-test.+\", container=\"app\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "usual-endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{namespace=\"resilience-workshop\",uri=\"/api/usual\"}[1m])) by (pod)/sum(rate(http_server_requests_seconds_count{ namespace=\"resilience-workshop\",uri=\"/api/usual\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"resilience-workshop\", status=~\"5..\",uri=\"/api/usual\"}[1m])) by (pod)",
       "legendFormat": "error {{pod}}"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"resilience-workshop\", status!~\"5..\",uri=\"/api/usual\"}[1m])) by (pod)",
       "legendFormat": "success {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "delayed-error-endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{namespace=\"resilience-workshop\",uri=\"/api/delayed-error\"}[1m])) by (pod)/sum(rate(http_server_requests_seconds_count{ namespace=\"resilience-workshop\",uri=\"/api/delayed-error\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"resilience-workshop\", status=~\"5..\",uri=\"/api/delayed-error\"}[1m])) by (pod)",
       "legendFormat": "error {{pod}}"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"resilience-workshop\", status!~\"5..\",uri=\"/api/delayed-error\"}[1m])) by (pod)",
       "legendFormat": "success {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "random-error-endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{namespace=\"resilience-workshop\",uri=\"/api/random-error\"}[1m])) by (pod)/sum(rate(http_server_requests_seconds_count{ namespace=\"resilience-workshop\",uri=\"/api/random-error\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"resilience-workshop\", status=~\"5..\",uri=\"/api/random-error\"}[1m])) by (pod)",
       "legendFormat": "error {{pod}}"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"resilience-workshop\", status!~\"5..\",uri=\"/api/random-error\"}[1m])) by (pod)",
       "legendFormat": "success {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "slow-db-query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{namespace=\"resilience-workshop\",uri=\"/api/slow-db-query\"}[1m])) by (pod)/sum(rate(http_server_requests_seconds_count{ namespace=\"resilience-workshop\",uri=\"/api/slow-db-query\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"resilience-workshop\", status=~\"5..\",uri=\"/api/slow-db-query\"}[1m])) by (pod)",
       "legendFormat": "error {{pod}}"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"resilience-workshop\", status!~\"5..\",uri=\"/api/slow-db-query\"}[1m])) by (pod)",
       "legendFormat": "success {{pod}}"
      }
     ]
    },
    {
     "title": "connection-pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(mongodb_driver_pool_waitqueuesize) by (pod)",
       "legendFormat": "waiting {{pod}}"
      },
      {
       "expr": "sum(mongodb_driver_pool_checkedout) by (pod)",
       "legendFormat": "active {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "pubsub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(spring_integration_send_seconds_sum{namespace=\"resilience-workshop\", type=\"channel\"}[1m])) by (pod)/sum(rate(spring_integration_send_seconds_count{namespace=\"resilience-workshop\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(spring_integration_send_seconds_count{namespace=\"resilience-workshop\"}[1m])) by (pod, result)",
       "legendFormat": "{{result}} {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}