apiVersion: v1
kind: Service
metadata:
  name: pubsub-emulator
  namespace: resilience-workshop
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8085
      targetPort: http
  selector:
    app: pubsub-emulator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-emulator
  namespace: resilience-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-emulator
  template:
    metadata:
      labels:
        app: pubsub-emulator
    spec:
      containers:
        - image: slamdev/resilience-workshop-pubsub-emulator
          imagePullPolicy: IfNotPresent
          name: app
          volumeMounts:
            - name: data-dir
              mountPath: /var/pubsub
          ports:
            - name: http
              containerPort: 8085
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
      volumes:
        - name: data-dir
          emptyDir: {}
      nodeSelector:
        node_pool: preemptible
      tolerations:
        - key: preemptible
          operator: Equal
          value: "true"
          effect: NoSchedule
